# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djswdc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='dc_conf',
            fields=[
                ('conf', models.IntegerField(primary_key=True, serialize=False)),
                ('menu', models.TextField()),
                ('help', models.TextField()),
                ('mode', models.CharField(max_length=30)),
                ('eat', models.CharField(max_length=30)),
                ('register', models.CharField(max_length=30)),
                ('change', models.CharField(max_length=30)),
                ('response', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='dc_data',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uid', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(default='noname', max_length=30)),
                ('breakfast_book', djswdc.models.ListTextField(default=[])),
                ('lunch_book', djswdc.models.ListTextField(default=[])),
                ('dinner_book', djswdc.models.ListTextField(default=[])),
                ('breakfast_eat', djswdc.models.ListTextField(default=[])),
                ('lunch_eat', djswdc.models.ListTextField(default=[])),
                ('dinner_eat', djswdc.models.ListTextField(default=[])),
                ('other_eat', djswdc.models.ListTextField(default=[])),
            ],
        ),
    ]
