# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djswdc', '0002_auto_20170612_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_data',
            name='name',
            field=models.CharField(default='noname', max_length=30),
        ),
    ]
